/* =========================================================
   STUDYNE - MAIN SCRIPT
   ========================================================= */
const AUTH_KEY = "studyne_current_user";
const ACCOUNTS_KEY = "studyne_accounts";
function getAccounts(){try{const data=JSON.parse(localStorage.getItem(ACCOUNTS_KEY));return Array.isArray(data)?data:[]}catch(e){return[]}}
function saveAccounts(accounts){localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(accounts))}
function normalizeIdentity(value){return String(value||"").trim().toLowerCase()}
function escapeHTML(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function getInitials(name){const words=String(name||"").trim().split(/\s+/).filter(Boolean);if(!words.length)return"U";if(words.length===1)return words[0].substring(0,2).toUpperCase();return(words[0][0]+words[words.length-1][0]).toUpperCase()}
function hariIni(){return new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}

const SUBMISSIONS_KEY = "studyne_submissions";
function getSubmissions(){try{const data=JSON.parse(localStorage.getItem(SUBMISSIONS_KEY));return Array.isArray(data)?data:[]}catch(e){return[]}}
function saveSubmissions(items){localStorage.setItem(SUBMISSIONS_KEY,JSON.stringify(items))}
function getSubmission(taskId,userId){return getSubmissions().find(x=>x.taskId===taskId&&x.userId===userId)||null}
function formatFileSize(bytes){const n=Number(bytes||0);if(n<1024)return n+" B";if(n<1024*1024)return (n/1024).toFixed(1)+" KB";return (n/(1024*1024)).toFixed(1)+" MB"}
function formatDateTime(value){if(!value)return"-";return new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function isPastDeadline(item){return Boolean(item.deadlineISO&&Date.now()>new Date(item.deadlineISO).getTime())}
function saveSubmission(task,courseId,user,file){return new Promise((resolve,reject)=>{if(!file){reject(new Error("Pilih file tugas terlebih dahulu."));return}if(file.size>10*1024*1024){reject(new Error("Ukuran file maksimal 10 MB."));return}if(isPastDeadline(task)){reject(new Error("Deadline tugas sudah berakhir."));return}const reader=new FileReader();reader.onload=function(){const all=getSubmissions();const submission={id:"SUB-"+Date.now(),taskId:task.id,courseId,userId:user.id,userName:user.nama,fileName:file.name,fileSize:file.size,fileType:file.type||"application/octet-stream",dataUrl:reader.result,submittedAt:new Date().toISOString()};const index=all.findIndex(x=>x.taskId===task.id&&x.userId===user.id);if(index>=0)all[index]=submission;else all.push(submission);saveSubmissions(all);resolve(submission)};reader.onerror=function(){reject(new Error("File tidak dapat dibaca. Silakan coba lagi."))};reader.readAsDataURL(file)})}
function deleteSubmission(taskId,userId){const all=getSubmissions().filter(x=>!(x.taskId===taskId&&x.userId===userId));saveSubmissions(all)}
function registerAccount(data){const{nama,identity,password,confirmPassword,prodi,semester,role}=data;if(!nama||!identity||!password||!confirmPassword||!prodi)return{success:false,message:"Semua data wajib diisi."};if(!["mahasiswa","dosen"].includes(role))return{success:false,message:"Jenis akun tidak valid."};if(password.length<8)return{success:false,message:"Password harus memiliki minimal 8 karakter."};if(password!==confirmPassword)return{success:false,message:"Konfirmasi password tidak sesuai."};if(role==="mahasiswa"&&!semester)return{success:false,message:"Semester wajib diisi untuk akun mahasiswa."};const accounts=getAccounts();if(accounts.some(a=>normalizeIdentity(a.identity)===normalizeIdentity(identity)))return{success:false,message:"Nomor identitas tersebut sudah terdaftar. Silakan masuk."};const account={id:"USR-"+Date.now(),nama:nama.trim(),identity:identity.trim(),password,role,prodi:prodi.trim(),semester:semester?String(semester):""};accounts.push(account);saveAccounts(accounts);return{success:true,account}}
function resetPassword(identity,role,newPassword,confirmPassword){const accounts=getAccounts();const index=accounts.findIndex(a=>normalizeIdentity(a.identity)===normalizeIdentity(identity)&&a.role===role);if(index<0)return{success:false,message:"Akun tidak ditemukan. Periksa identitas dan jenis akun."};if(!newPassword||newPassword.length<8)return{success:false,message:"Password baru harus memiliki minimal 8 karakter."};if(newPassword!==confirmPassword)return{success:false,message:"Konfirmasi password tidak sesuai."};accounts[index].password=newPassword;saveAccounts(accounts);return{success:true,message:"Password berhasil diperbarui. Silakan masuk kembali."}}
function login(identity,password,role){const account=getAccounts().find(item=>normalizeIdentity(item.identity)===normalizeIdentity(identity)&&item.password===password&&item.role===role);if(!account)return{success:false,message:"Identitas, password, atau jenis akun tidak sesuai."};const session={id:account.id,nama:account.nama,identity:account.identity,role:account.role,prodi:account.prodi||"",semester:account.semester||"",loginAt:new Date().toISOString()};localStorage.setItem(AUTH_KEY,JSON.stringify(session));return{success:true,user:session}}
function getUser(){try{return JSON.parse(localStorage.getItem(AUTH_KEY))||null}catch(e){return null}}
function logout(){localStorage.removeItem(AUTH_KEY);window.location.href="login.html"}
function requireAuth(requiredRole=null){const user=getUser();if(!user){window.location.href="login.html";return null}if(requiredRole&&user.role!==requiredRole){window.location.href=user.role==="dosen"?"dashboard-dosen.html":"dashboard.html";return null}return user}
function renderSidebar(activePage=""){
    const sidebar=document.getElementById("sidebar");if(!sidebar)return;const user=getUser();if(!user)return;const isDosen=user.role==="dosen";const dashboardLink=isDosen?"dashboard-dosen.html":"dashboard.html";const dashboardActive=activePage==="dashboard"?"active":"";const coursesActive=activePage==="courses"?"active":"";const menuMahasiswa=`<a href="${dashboardLink}" class="sidebar-link ${dashboardActive}"><span class="nav-icon">⌂</span>Dashboard</a><a href="courses.html" class="sidebar-link ${coursesActive}"><span class="nav-icon">▣</span>Mata Kuliah</a><a href="${dashboardLink}#jadwal" class="sidebar-link"><span class="nav-icon">◷</span>Jadwal</a><a href="${dashboardLink}#nilai" class="sidebar-link"><span class="nav-icon">▤</span>Nilai & Presensi</a><a href="${dashboardLink}#notifikasi" class="sidebar-link"><span class="nav-icon">🔔</span>Notifikasi</a>`;const menuDosen=`<a href="${dashboardLink}" class="sidebar-link ${dashboardActive}"><span class="nav-icon">⌂</span>Dashboard</a><a href="courses.html" class="sidebar-link ${coursesActive}"><span class="nav-icon">▣</span>Mata Kuliah</a><a href="${dashboardLink}#mahasiswa" class="sidebar-link"><span class="nav-icon">👥</span>Mahasiswa</a><a href="${dashboardLink}#tugas" class="sidebar-link"><span class="nav-icon">📝</span>Tugas</a><a href="${dashboardLink}#notifikasi" class="sidebar-link"><span class="nav-icon">🔔</span>Notifikasi</a>`;
    sidebar.innerHTML=`<aside class="sidebar"><div class="sidebar-top"><div class="sidebar-brand"><a href="${dashboardLink}"><img src="images/logo.svg" alt="STUDYNE"></a><button type="button" class="sidebar-close" onclick="toggleSidebar()">×</button></div><div class="user-mini"><div class="avatar">${escapeHTML(getInitials(user.nama))}</div><div class="user-mini-info"><strong>${escapeHTML(user.nama)}</strong><span>${isDosen?"Dosen":"Mahasiswa"}</span></div></div><nav class="sidebar-nav"><span class="nav-label">MENU UTAMA</span>${isDosen?menuDosen:menuMahasiswa}</nav></div><div class="sidebar-bottom"><button type="button" class="logout-btn" data-logout><span class="nav-icon">↪</span>Keluar</button></div></aside>`;
    const logoutButton=sidebar.querySelector("[data-logout]");if(logoutButton)logoutButton.addEventListener("click",logout);sidebar.querySelectorAll(".sidebar-link").forEach(link=>link.addEventListener("click",()=>{if(window.innerWidth<=900)toggleSidebar(false)}));
}
function toggleSidebar(forceState=null){const sidebar=document.querySelector(".sidebar");const backdrop=document.getElementById("sidebarBackdrop");if(!sidebar)return;const open=forceState!==null?forceState:!sidebar.classList.contains("open");sidebar.classList.toggle("open",open);if(backdrop)backdrop.classList.toggle("show",open)}
document.addEventListener("DOMContentLoaded",()=>{const backdrop=document.getElementById("sidebarBackdrop");if(backdrop)backdrop.addEventListener("click",()=>toggleSidebar(false))});
function courseCardHTML(course){const progress=Math.min(100,Math.max(0,Number(course.progress||0)));const color=BANNER_COLORS[Math.abs(String(course.id).split("").reduce((a,c)=>a+c.charCodeAt(0),0))%BANNER_COLORS.length];return`<article class="course-card" onclick="window.location.href='course.html?id=${encodeURIComponent(course.id)}'"><div class="course-banner" style="background:${color}"><span>${escapeHTML(course.code)}</span></div><div class="course-card-body"><div class="course-card-top"><span class="course-code">${escapeHTML(course.code)}</span><span class="course-sks">${course.sks} SKS</span></div><h3>${escapeHTML(course.name)}</h3><div class="course-info"><span>◷ ${escapeHTML(course.schedule)}</span><span>👤 ${escapeHTML(course.lecturer)}</span></div><div class="course-progress"><div class="progress-header"><span>Progress</span><strong>${progress}%</strong></div><div class="progress-bar"><div style="width:${progress}%"></div></div></div></div></article>`}
